package com.jp.fastadapterissue.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jp.fastadapterissue.entity.TradeItem;

import com.jp.fastadapterissue.dao.TradeItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tradeItemDaoConfig;

    private final TradeItemDao tradeItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tradeItemDaoConfig = daoConfigMap.get(TradeItemDao.class).clone();
        tradeItemDaoConfig.initIdentityScope(type);

        tradeItemDao = new TradeItemDao(tradeItemDaoConfig, this);

        registerDao(TradeItem.class, tradeItemDao);
    }
    
    public void clear() {
        tradeItemDaoConfig.clearIdentityScope();
    }

    public TradeItemDao getTradeItemDao() {
        return tradeItemDao;
    }

}
