package com.jp.fastadapterissue.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jp.fastadapterissue.entity.TradeEntity;

import com.jp.fastadapterissue.dao.TradeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tradeEntityDaoConfig;

    private final TradeEntityDao tradeEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tradeEntityDaoConfig = daoConfigMap.get(TradeEntityDao.class).clone();
        tradeEntityDaoConfig.initIdentityScope(type);

        tradeEntityDao = new TradeEntityDao(tradeEntityDaoConfig, this);

        registerDao(TradeEntity.class, tradeEntityDao);
    }
    
    public void clear() {
        tradeEntityDaoConfig.clearIdentityScope();
    }

    public TradeEntityDao getTradeEntityDao() {
        return tradeEntityDao;
    }

}
